### ISSUE TITLE
Matomo Marketplace Install Page Showing Non-Matomo Plugins

### ISSUE THREAD

**Issue by danieljwonder** [matomo-org/matomo-marketplace-for-wordpress#4]
When visiting the Install Plugins page of the Matomo Marketplace plugin, other plugins unrelated to Matomo are showing. For example, one of my sites is recommending lots of Genesis plugins; I'm using the Genesis theme. Based on the Install Plugin URL, I think this might be related to the framework being used for this feature: http://tgmpluginactivation.com/

Upon further investigation I can confirm that all of the non-Matomo plugins listed on the Matomo page are the same as the ones being listed on my theme's recommended plugin page. The themes recommendation also appears to be using tgmpa but is only showing Genesis plugins, so there must be a way to limit conflicts.

**Comment by tsteur** [comment]
Seems this dependency doesn't offer anything to workaround this problem and they won't in the future either unfortunately: https://github.com/TGMPA/TGM-Plugin-Activation/issues/735

Not sure if/what we can do about it. I'll get in touch with you by email @danielmcclure

**Comment by tsteur** [comment]
Thanks @danielmcclure this will be fixed in next update
