### ISSUE TITLE
Make sure the plugin works with new WordPress 6

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo-marketplace-for-wordpress#6]
refs https://github.com/matomo-org/matomo-for-wordpress/issues/592

see https://make.wordpress.org/core/6-0/

There will be a first release from RC1 from 3 May 2022 with the release on 24 May 2022. This means we probably need to start working on this soon.

Many people will upgrade to WordPress 6 quickly so we need to make sure that everything works nicely with this version on release day (and ideally bit before).

We have [2 dependencies that hook into WordPress](https://github.com/matomo-org/matomo-marketplace-for-wordpress/blob/live/composer.json#L3-L4) around updating plugins etc so I assume there might be some updating needed (or not but in any case should test it still works).

**Comment by mattmary** [comment]
@tsteur nothing to report in the ui on wordpress 6.

**Comment by tsteur** [comment]
Awesome 👍  great to hear 🎉
